# Generated by Django 3.1.4 on 2020-12-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('date', 'client', 'employee'), name='unique_contact'),
        ),
    ]
