# Generated by Django 3.1.4 on 2020-12-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201218_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='employees', through='contacts.Contact', to='contacts.Client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.employee'),
        ),
    ]
